### ISSUE TITLE
Support more theme tokens

### ISSUE THREAD

**Issue by yukukotani** [kuma-ui/kuma-ui#257]
[The doc](https://www.kuma-ui.com/docs/Theme/CustomizingTheme#theme-tokens) says that kuma-ui want to support more theme tokens. To follow [Chakra UI](https://chakra-ui.com/docs/styled-system/theme), we need to implement the primitive tokens below:

- [x] colors
- [x] fonts
- [x] fontSizes
- [x] fontWeights
- [x] lineHeights
- [x] letterSpacings
- [x] breakpoints
- [x] space
- [x] sizes
- [x] radii
- [x] zIndices

Panda CSS supports more detail tokens like [borders](https://panda-css.com/docs/theming/tokens#borders).
Let me clarify which tokens should be supported in kuma-ui on this issue, so that I can work on this.

**Comment by poteboy** [comment]
@yukukotani 
In our meeting a week ago, we decided to support `font`, `fontSize`, `fontWeights`, `lineHeights`, and `letterSpacings`. This task has already been assigned to another maintainer, @taishinaritomi , so there might be some overlap with what he's currently working on. It would be a good idea to discuss and split the work with him!
Also, thank you for showing initiative to tackle this issue :)

**Comment by yukukotani** [comment]
@poteboy Thanks for the quick response!

The other tokens are won't be supported, or just not discussed yet? If latter, how about that taishi-san works on typography related tokens and I work on the others?

**Comment by poteboy** [comment]
@yukukotani 
That sounds like a great idea, go ahead with it🙏. Regarding the `spacing` token, I've been considering making it so that, like Chakra, the default is 0.25rem and setting `p={4}` would make it 1rem. I think it would be good to be able to set the default for this. I've created `packages/system/src/toCSS.ts` with this in mind, so please check it out!

**Comment by yukukotani** [comment]
@poteboy Okay!

>  I've been considering making it so that, like Chakra, the default is 0.25rem and setting p={4} would make it 1rem. 

Do you mean that Kuma UI provides default tokens? I'm little confused because the doc says that [Kuma UI doesn't come with a default theme](https://www.kuma-ui.com/docs/Theme/CustomizingTheme#:~:text=it%20doesn%27t%20come%20with%20a%20default%20theme).

Maybe that means just components are headless?

**Comment by yukukotani** [comment]
Finally, all the tokens listed have been supported. Let's close this

**Comment by poteboy** [comment]
Thank you so much 🐻‍❄️👋
