### ISSUE TITLE
Consider Replacing `ts-pattern` with TypeScript's satisfies or ESLint's `switch-exhaustiveness-check` for Performance Gains 🤔

### ISSUE THREAD

**Issue by poteboy** [kuma-ui/kuma-ui#288]
Currently, in Kuma UI, we utilize the [`ts-pattern`](https://github.com/gvergnaud/ts-pattern) for exhaustive type inference checks through pattern matching, as demonstrated below:

```ts
const isComponentProps =
  (componentName: ComponentName) => (propName: string) => {
    return match(componentName)
      .with("Box", () => isBoxProps(propName))
      // other code
      .with("Grid", () => isGridProps(propName))
      .exhaustive();
  };
```

However, having `ts-pattern` as a dependency in both `@kuma-ui/core` and `@kuma-ui/compiler` has raised some concerns:

- **Bundle Size** : We'd ideally like to minimize our bundle size, and avoiding this dependency can help achieve that.
- **Performance**: I conducted a benchmark comparison between the native JavaScript switch and ts-pattern. Unfortunately, ts-pattern seems to be considerably slower. Check out the code and results here:

```ts
import { match } from "ts-pattern";
import { add, cycle, complete, suite } from "benny";

export type Data =
  | { type: "text"; content: string }
  | { type: "number"; value: number };

export const testData: Data[] = Array.from({ length: 1000 }, (_, index) =>
  index % 2 === 0
    ? { type: "text", content: "Hello, world!" + index }
    : { type: "number", value: index }
);

function process(data: Data) {
  return match(data)
    .with({ type: "text" }, (x) => x.content.length)
    .with({ type: "number" }, (x) => x.value * 2)
    .exhaustive();
}

function processNative(data: Data) {
  switch (data.type) {
    case "text":
      return data.content.length;
    case "number":
      return data.value * 2;
  }
}

suite(
  "Pattern Matching Benchmark",

  add("ts-pattern", () => {
    for (const data of testData) {
      process(data);
    }
  }),

  add("Native JS", () => {
    for (const data of testData) {
      processNative(data);
    }
  }),

  cycle(),

  complete()
);
```

Result:

```
ts-pattern: 5,985 ops/s, ±0.51%     | slowest, 98.31% slower
Native JS: 354,529 ops/s, ±0.28%   | fastest
```
- **HMR Speed**: For Hot Module Replacement performance improvements, removing runtime intervention from ts-pattern might be beneficial.

Given the introduction of `satisfies` in [TypeScript v4.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html), and the availability of the `switch-exhaustiveness-check` rule from [ESLint](https://typescript-eslint.io/rules/switch-exhaustiveness-check/), perhaps it's time to reconsider our choice of pattern matching utility.

I'm inclined to make this a _**good first issue**_ if the core members, @kotarella1110  and @taishinaritomi , are on board with this change 🤞

**Comment by AdePhil** [comment]
Hi @poteboy I would like to work on this. Let me know if it's good to go. Thanks.

**Comment by poteboy** [comment]
@AdePhil 
Absolutely! Go for it. Really appreciate it
