### ISSUE TITLE
Publish the snapshot package of main branch automatically

### ISSUE THREAD

**Issue by yukukotani** [kuma-ui/kuma-ui#299]
Chakra UI publishes the snapshot package on every commit on the main branch.
https://www.npmjs.com/package/@chakra-ui/react/v/0.0.0-dev-20230822134434

Kuma UI is also under the heavy development and we'd like to use the latest version without waiting for stable releases.

**Comment by yukukotani** [comment]
of course I can work on this if it sounds good

**Comment by poteboy** [comment]
@yukukotani 
That's a great idea! My only concern is if every publish creates a release, it might become noisy. If releases are only generated for patch versions and above, that'd be perfect. 🙏

**Comment by yukukotani** [comment]
@poteboy Thanks, will work on this!
Actually the snapshot release won't bump the version. The version tag would be like `1.1.3-dev-${TIMESTAMP}`, so that the semantic version is fixed and the timestamp guarantees the uniqueness.

**Comment by yukukotani** [comment]
@poteboy Ah I see, agree with you! Will just publish to npm and not create GitHub release for snapshots.
