### ISSUE TITLE
Allow using theme tokens in css and styled

### ISSUE THREAD

**Issue by seagullua** [kuma-ui/kuma-ui#318]
Currently, using theme tokens to style third-party components is impossible.

It would be nice to have possibility to write

```
className={css`
                      color: theme("colors.primary");
                    `}
```

And have `theme("colors.primary")` replaced with real value at the build

Alternatively, it kuma may export all theme tokens as CSS variables so you can write `var(--kuma-colors-primary)`.

**Comment by poteboy** [comment]
@seagullua 
Absolutely, but I am pondering the API design. I would think it is easier to just write `colors.primary`. What do you say?

**Comment by seagullua** [comment]
@poteboy, thanks for a quick reply. 

I think the good idea will be to stick with something like theme(...) or token(...)

1. It will be easier to parse and harder to make the wrong replacement. For example, right now if I define breakpoint: sm. It replaces `@media (... small)` with `@media (... 450pxall)`. Some keywords will solve lots of such issues.
2. Right now, Webstorm will show an error for `colors.xxxx ` but not for keywords.

<img width="847" alt="Screenshot 2023-09-04 at 9 57 29 AM" src="https://github.com/kuma-ui/kuma-ui/assets/759038/f5a4b6b6-bc51-4ac1-ae25-3e316afad982">

**Comment by poteboy** [comment]
> Webstorm will show an error for colors.xxxx  but not for keywords

Thank you for your suggestion. I hadn't considered the potential issues with editors indicating errors for `colors.xxxx`, but it's certainly something worth keeping in mind.

**Comment by seagullua** [comment]
@poteboy Do you think the implementation can take long? 

I was checking the source code, and it looks like it can be straightforward. You need a regular expression to catch all theme(...) in the code and match the known keys.

I would have implemented it, but I did not figure out how to debug babel preprocessors.

**Comment by poteboy** [comment]
@seagullua 

I suspect that the `theme(...)` function might currently be recognized as a CSS function in your editor. Considering this, I have a concern that using a generic name like theme for this function might clash with future web standards. So, how about we opt for a more distinctive syntax such as `t(...)` to avoid potential naming conflicts?

Regarding debugging, it seems like the viable approach for now is to make modifications in the packages, build it, and then verify the behavior within a project in the playground directory. You might find it easier to check the AST transformations in the browser using the [vite-plugin-inspect](https://github.com/antfu/vite-plugin-inspect) within the `playground/vite project`.

**Comment by seagullua** [comment]
@poteboy Sure t() will be great as well.

**Comment by poteboy** [comment]
@seagullua 
Okay, I've assigned this issue to you. Please let me know if you encounter any difficulties implementing this.

**Comment by seagullua** [comment]
@poteboy A few more proposals relating to this ticket

1. Allow shortcuts `t("c.primary")` as a synonym to `t("colors.primary")`
2. Lots of CSS to js libraries allow using integers instead of pixels to make a consistent UI more simple, so it may be a good idea to have. So you can basically write `margin-bottom: t(1);`
- t(1) -> 8px
- t(2) -> 16px

What do you think?

**Comment by seagullua** [comment]
@poteboy I have submitted pull request
