### ISSUE TITLE
Support styled.div`...` syntax, like styled-components

### ISSUE THREAD

**Issue by mmkal** [kuma-ui/kuma-ui#341]
Hi, this looks very promising - we're looking into kuma as a replacement for styled-components that works without overhead for react server components. We have hundreds of files and thousands of components to migrate, though, so the closer we can get to something with an API like styled-components, the better.

I noticed in the docs that this is how a div would be styled:

```ts
const MyDiv = styled('div')`
  color: blue;
`
```

Would you consider adding this syntax, to match styled-components and make our migration _much_ easier?

```ts
const MyDiv = styled.div`
  color: blue;
`
```

(as well as equivalents for the various HTML element types)

It could be a non-breaking, thin wrapper for the existing syntax. I'd be happy to contribute a PR for this if it'd be accepted.

**Comment by poteboy** [comment]
@mmkal 
Hey, thanks for reaching out. Indeed, a syntax that more closely resembles the existing API is desirable. Feel free to submit a PR! If you encounter any issues, I'd be happy to help. 

The related files are probably `packages/compiler/src/processTaggedTemplateExpression.ts` and `packages/core/src/styled.ts`.
