### ISSUE TITLE
Custom theme does not work correctly with pseudo-elements

### ISSUE THREAD

**Issue by tomoyuki-hiranuma** [kuma-ui/kuma-ui#349]
# Description
Custom theme does not work correctly with pseudo elements, such as `_hover`, `_active` in nextjs project, as the title says.

## Environment
Nextjs@13.4.19
kuma-ui@1.4.1
pnpm@8.7.4
node@18.17.1

## Demo
1. Pull [kumaui-next-problem-minimal-sample](https://github.com/tomoyuki-hiranuma/kumaui-next-problem-minimal-sample)
2. Run `pnpm install`
3. Run `pnpm run dev`
4. Open [http://localhost:3000](http://localhost:3000)
5. You can see the `bgColor` in the text does not changed when hovering state, and the `bgColor` in the button does not changed when active state.

**Comment by poteboy** [comment]
@tomoyuki-hiranuma 
Thank you for raising this issue. The generation of styles is handled in `packages/system/src/generator.ts`, so that area seems to be suspicious.

**Comment by tomoyuki-hiranuma** [comment]
@poteboy 
Thank you for helpful information.
I will try it 🙌
