### ISSUE TITLE
Cannot use background-image CSS property.

### ISSUE THREAD

**Issue by yodakaEngineer** [kuma-ui/kuma-ui#353]
# Description
I wrote this code.
```
<Box
      backgroundImage={'url(/topImage.jpg)'}
      width={'100%'}
      height={'300px'}
      backgroundSize={'cover'}
    >
      <div ref={ref}>
      </div>
    </Box>
```

But, background-image was not generated. Console has no error.
<img width="246" alt="image" src="https://github.com/kuma-ui/kuma-ui/assets/44350989/d9aa186c-9b72-4548-ac2a-7b63ac119e10">

# Environment
Nextjs@13.4.4
kuma-ui@1.5.0
kuma-ui/next-plugin@1.1.10
node@16.20.0

**Comment by poteboy** [comment]
Fixed in #371
