### ISSUE TITLE
How to use a Next.JS font?

### ISSUE THREAD

**Issue by kul-sudo** [kuma-ui/kuma-ui#356]
Should I just do it like that? :point_down: 
```tsx
import type { FC } from 'react'
import type { AppProps } from 'next/app'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

const App: FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <main className={inter.className}>
      <Component {...pageProps} />
    </main>
  )
}

export default App
```

Or is there a way to do it maybe through the configuration of the library?

**Comment by yukukotani** [comment]
@kul-sudo Kuma doesn't provide the special integration for next/font but your code would work well. Let me know if you have any proposal of API or feature that Kuma should provide.

**Comment by kul-sudo** [comment]
> @kul-sudo Kuma doesn't provide the special integration for next/font but your code would work well. Let me know if you have any proposal of API or feature that Kuma should provide.

Yeah, I have actually considered going into the code making a few pull requests, so I'll maybe do it in the future.

**Comment by yukukotani** [comment]
Let me close this for now since we can use next/font with Kuma, but any PR is welcome!
