### ISSUE TITLE
Using the "styled" tag in runtime is not supported.

### ISSUE THREAD

**Issue by doksara** [kuma-ui/kuma-ui#373]
Hi, I am switching from `styled-components` to `kuma-ui` and got the mentioned error as soon as I replaced the first line:

`import styled from 'styled-components'`
to
`import { styled } from "@kuma-ui/core"`

styles.ts
--------
```
import { styled } from "@kuma-ui/core"

export const Section = styled("section")`
  margin: 0 var(--horizontal-gutter);
`
```

Introduction.tsx
----------------
```
import * as S from "./styles"
import { Box } from "@kuma-ui/core"

const Introduction = () => {
  return (
    <S.Section aria-describedby="section-introduction-title">
      <Box my={96}>I am sample text</Box>
    </S.Section>
  )
}

export default Introduction
```

**Comment by poteboy** [comment]
@doksara 
Have you set up our plugin? Depending on the framework with which you're using Kuma, you'll need to set up the plugin as outlined here:
https://www.kuma-ui.com/docs/install#setting-up-kuma-ui.

**Comment by doksara** [comment]
@poteboy 
Yeah, I have followed the installation guide from official docs. 

I am using:
```
    "@kuma-ui/core": "^1.5.2",
    "next": "^12.1.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

**Comment by poteboy** [comment]
@doksara 
Can I see your next.config.js?

**Comment by doksara** [comment]
```
const { withKumaUI } = require("@kuma-ui/next-plugin")

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = withKumaUI(nextConfig)

```

**Comment by poteboy** [comment]
@doksara 
It seems there might be an incompatibility between the older version of Next.js and our plugin. We've specified the peer dependency version of Next.js to be 13.4.5. Could you please upgrade your Next.js to version 13.4.5 or newer?

**Comment by doksara** [comment]
Still getting the same error. This is my full list of dependencies:

```
  "dependencies": {
    "@kuma-ui/core": "^1.5.2",
    "framer-motion": "^6.3.1",
    "lottie-web": "^5.12.2",
    "next": "^13.4.5",
    "perfect-scrollbar": "^1.5.0",
    "react": "^18.2.0",
    "react-calendar": "^4.5.0",
    "react-dom": "^18.2.0",
    "react-intl": "^6.5.1",
    "react-is": "^17.0.2",
    "react-measure": "^2.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@kuma-ui/next-plugin": "^1.1.12",
    "@types/node": "^20",
    "@types/react": "^17.0.2",
    "@types/react-dom": "^17.0.2",
    "eslint": "^8",
    "eslint-config-next": "13.5.5",
    "react-intersection-observer": "^8.31.0",
    "typescript": "^5"
  },
```

**Comment by doksara** [comment]
I literally created a fresh new project with create-next-app and got error as soon as I created first styled component:

![Screenshot 2023-11-02 at 18 33 25](https://github.com/kuma-ui/kuma-ui/assets/32953370/b08cd025-c92c-40cf-b10e-006c712f0735)

**Comment by poteboy** [comment]
Judging by the error message, it seems you've created a styled component in a .ts file instead of a .tsx file.

**Comment by doksara** [comment]
@poteboy That solved the last issue, thank you. Regarding the first one, I found out the issue - it was in package `babel-plugin-styled-components` and also my .babelrc configuration which contained following setting: 

`"plugins": ["styled-components"]`

After those were removed, I the error was gone.

**Comment by poteboy** [comment]
@doksara 
Glad to hear it's resolved! I'll go ahead and close this issue 👍

**Comment by doksara** [comment]
One additional info for others reading this -> You have to completely remove your `.babelrc` configuration, otherwise you will still get the error.

**Comment by agsmartwolf** [comment]
I have the same issue but with `css` function.
I have deps:

"next": "14.0.0",
"@kuma-ui/next-plugin": "1.1.12",
"@kuma-ui/core": "1.5.2",


next js config:
```const { withKumaUI } = require("@kuma-ui/next-plugin");

/** @type {import('next').NextConfig} */
const config = {
	images: {
		remotePatterns: [
			{
				hostname: "*",
			},
		],
	},
	experimental: {
		typedRoutes: false,
	},
	reactStrictMode: true,
};

module.exports = withKumaUI(config);
// export default config```


kuma config
```import { createTheme } from "@kuma-ui/core";

const theme = createTheme({
	colors: {
		white: "#ffffff",
		gray: "#f5f4f4",
	},
	fontSizes: {
		xs: "1.1rem",
		sm: "1.2rem",
		base: "1.4rem",
		md: "1.6rem",
		lg: "2.4rem",
		xl: "3.2rem",
	},
});

type UserTheme = typeof theme;

declare module "@kuma-ui/core" {
	export interface Theme extends UserTheme {}
}

export default theme;```

I also use tailwind css, because I'm in process of migration and still need it.
