### ISSUE TITLE
Static styles are not applied with @kuma-ui/webpack-plugin v1.3.0

### ISSUE THREAD

**Issue by ygkn** [kuma-ui/kuma-ui#402]
Hello,

I've encountered a static styling issue with @kuma-ui/webpack-plugin 1.3.0: static stylings are not applied.

## Steps to Reproduce
1. Switch to branch `main` (now f5125562c8a2164c31346be981c1ec734245d583).
2. Run `pnpm start`

### At the branch `main`

<img width="1512" alt="image" src="https://github.com/kuma-ui/kuma-ui/assets/14973783/5e821def-780e-4e8a-910f-68ceac963747">

Static styles (color and font size of the text "Hello World", padding of green boxes) are not applied.

### At the tag `@kuma-ui/webpack-plugin@1.2.7` (1cc40f4ed0005581e9392f34d8869b2ce5b47b32)

<img width="1512" alt="image" src="https://github.com/kuma-ui/kuma-ui/assets/14973783/7e879755-21c4-4d01-887d-d5cd7051d3b2">

Static styles and dynamic styles are both applied.

## Workaround

Downgrading to `@kuma-ui/webpack-plugin` version v1.2.7 or lower.

Best,

**Comment by ygkn** [comment]
I have confirmed that this issue is resolved by #399.

**Comment by poteboy** [comment]
@ygkn 
Thank you for pointing that out. I have merged #399  into main and released it, so it should be working correctly now :)

**Comment by ygkn** [comment]
I've updated Kuma UI and confirmed it works in my project. Thanks for the quick action!
