### ISSUE TITLE
Feedback for “Installation”

### ISSUE THREAD

**Issue by jmblog** [kuma-ui/kuma-ui#404]
Hi there,

Noticed a small mix-up: `@kuma-ui/core` uses `npm` for its install command, but `@kuma-ui/next-plugin` goes with `pnpm`. It's a bit confusing 😅. Could we stick to one for both? Would make things smoother.

Cheers!

**Comment by poteboy** [comment]
Thanks for the feedback! Actually, this just indicates that Kuma UI can be installed with any package manager, thus we provide npm, yarn, pnpm sections so you can stick to any preferable package manager you like!

<img width="527" alt="スクリーンショット 2024-03-04 23 30 08" src="https://github.com/kuma-ui/kuma-ui/assets/59927325/c2668db0-b6f8-42db-86e3-b9e82f93d8af">
