### ISSUE TITLE
NEXT 14 - Error: Using the "styled" tag in runtime is not supported.

### ISSUE THREAD

**Issue by dfiedlerx** [kuma-ui/kuma-ui#407]
I'm not able to run next14 together with Kuma UI, even when it's in a completely new project. Anyone else suffering from this problem?

Here is the minimum repository where I am reproducing the error:

https://github.com/dfiedlerx/next14_kuma_styled_runtime

<img width="840" alt="image" src="https://github.com/kuma-ui/kuma-ui/assets/32338795/c0aadf5b-1a68-4fe3-bdbb-8ca00efac4cc">

**Comment by poteboy** [comment]
You imported 'styled' using a relative path. Replace it like this, and it should work:
```tsx
- import { styled } from "../../node_modules/@kuma-ui/core/dist/styled";
+ import { styled } from "@kuma-ui/core";
```
