### ISSUE TITLE
"_before" prop is missing "content" attribute

### ISSUE THREAD

**Issue by JT501** [kuma-ui/kuma-ui#414]
Hi there, I found a bug in **_before** prop.
The **content** attribute is missing.

I have to use **css** api as a workaround.

Core version: 1.5.7

![Screenshot 2024-05-09 at 1 50 17 PM](https://github.com/kuma-ui/kuma-ui/assets/19503156/432e221f-5a5f-49f0-a8ac-dec17b168166)

Wordaround:

```js
<Flex
        flexDirection={'column'}
        position={'relative'}
        pb={'spacings.2'}
        _before={{
          display: 'block',
          position: 'absolute',
          left: 0,
          bottom: 0,
          right: 0,
          height: '1px',
          background: 'colors.line',
        }}
        className={css`
          &::before {
              content: '';
          }
        `}
      >
       ....
</Flex>
```

**Comment by poteboy** [comment]
Thanks for the report! This should be resolved once #393 is merged. Will take a look!
