### ISSUE TITLE
Non-English literals are rendered with escape sequence

### ISSUE THREAD

**Issue by yahiro07** [kuma-ui/kuma-ui#415]
Hi, Thank you for a nice library.

I tried latest Kuma setup with wasm enabled and found a bug.

For an input component, If I pass string literal to the value prop like
```tsx
<Input type="text" value="コメント" width="250px" />
```

The rendered text is escaped.
<img width="277" alt="スクリーンショット 2024-05-29 0 09 28" src="https://github.com/kuma-ui/kuma-ui/assets/321700/9fe71f81-74ad-4e7d-bf5e-1b94418d0f7f">

I also noticed the same behavior for other props like `placeholder` and `title`.

I'm using  `"@kuma-ui/vite": "1.3.1"` and have `plugins: [react(), KumaUI({ wasm: true })]` in `vite.config.ts`.
It works correctly when I remove `{ wasm: true }` from the config.

**Comment by poteboy** [comment]
@yahiro07 
Thank you for the report! You are right, this is indeed a bug. I'll look into it!
